// ============================================================
//  ALMA MÍA — Lista de Productos
//  Editá este archivo para agregar, modificar o eliminar productos.
//  Cada producto tiene: id, nombre, categoria, precio, descripcion, imagen
//  Las categorías válidas son: "Marroquinería", "Plata", "Autor", "Acero"
//  Para ocultar un producto sin borrarlo, agregá: oculto: true
// ============================================================

const PRODUCTOS_BASE = [

    // === PLATA 925 ===
    { id: 301, nombre: "Aros Gota Inflada",        categoria: "Plata",  precio: "Consultar", descripcion: "Plata 925. Diseño minimalista con volumen.",                          imagen: "https://raw.githubusercontent.com/tute04/ALMA-MIA/main/WhatsApp%20Image%202025-12-23%20at%2021.44.56.jpeg" },
    { id: 303, nombre: "Set Silver Balls",          categoria: "Plata",  precio: "Consultar", descripcion: "Gargantilla y pulsera bolas plata y cadena.",                        imagen: "https://raw.githubusercontent.com/tute04/ALMA-MIA/main/WhatsApp%20Image%202025-12-23%20at%2021.44.56%20(1).jpeg" },
    { id: 304, nombre: "Set Amatista",              categoria: "Plata",  precio: "Consultar", descripcion: "Cristales violetas y dije solitario.",                               imagen: "https://raw.githubusercontent.com/tute04/ALMA-MIA/main/WhatsApp%20Image%202025-12-23%20at%2021.44.57%20(2).jpeg" },
    { id: 310, nombre: "Set Multicolor",            categoria: "Plata",  precio: "Consultar", descripcion: "Cristales facetados multicolor y dije.",                             imagen: "https://raw.githubusercontent.com/tute04/ALMA-MIA/main/WhatsApp%20Image%202025-12-23%20at%2021.44.57%20(3).jpeg" },
    { id: 305, nombre: "Dijes Plata Lisos",         categoria: "Plata",  precio: "Consultar", descripcion: "Luna, Círculo Cristal y Gota.",                                     imagen: "https://raw.githubusercontent.com/tute04/ALMA-MIA/main/WhatsApp%20Image%202025-12-23%20at%2021.44.57.jpeg" },
    { id: 306, nombre: "Anillos Plata Boho",        categoria: "Plata",  precio: "Consultar", descripcion: "Diseños anchos, hojas y texturas.",                                  imagen: "https://raw.githubusercontent.com/tute04/ALMA-MIA/main/WhatsApp%20Image%202025-12-23%20at%2021.44.55.jpeg" },
    { id: 307, nombre: "Dijes Plata Labrados",      categoria: "Plata",  precio: "Consultar", descripcion: "Cruz, Rosa y Filigrana.",                                            imagen: "https://raw.githubusercontent.com/tute04/ALMA-MIA/main/WhatsApp%20Image%202025-12-23%20at%2021.44.57%20(1).jpeg" },

    // === MARROQUINERÍA — NUEVAS FOTOS 2026 ===
    { id: 1001, nombre: "Bolso Suela Urbano",       categoria: "Marroquinería", precio: "Consultar", descripcion: "Bolso de cuero color suela con manijas cortas y detalles metálicos. Ideal para el día a día.",         imagen: "https://raw.githubusercontent.com/tute04/ALMA-MIA/main/WhatsApp%20Image%202026-01-29%20at%2000.16.10%20(1).jpeg" },
    { id: 1002, nombre: "Bandolera Chocolate Chic", categoria: "Marroquinería", precio: "Consultar", descripcion: "Bandolera de cuero marrón chocolate, con correa ajustable y cierre seguro. Elegancia casual.",         imagen: "https://raw.githubusercontent.com/tute04/ALMA-MIA/main/WhatsApp%20Image%202026-01-29%20at%2000.16.10%20(2).jpeg" },
    { id: 1003, nombre: "Sobre Nude Minimal",       categoria: "Marroquinería", precio: "Consultar", descripcion: "Sobre de cuero nude, diseño minimalista y cierre metálico. Perfecto para eventos o salidas nocturnas.", imagen: "https://raw.githubusercontent.com/tute04/ALMA-MIA/main/WhatsApp%20Image%202026-01-29%20at%2000.16.10.jpeg" },
    { id: 1004, nombre: "Mochila Taupe Casual",     categoria: "Marroquinería", precio: "Consultar", descripcion: "Mochila de cuero taupe, amplia y cómoda, con bolsillos frontales y detalles en dorado.",               imagen: "https://raw.githubusercontent.com/tute04/ALMA-MIA/main/WhatsApp%20Image%202026-01-29%20at%2000.16.11.jpeg" },
    { id: 1008, nombre: "Cartera Cuero Trenzado",   categoria: "Marroquinería", precio: "Consultar", descripcion: "Cartera de cuero con detalles trenzados y herrajes dorados. Estilo artesanal.",                         imagen: "https://raw.githubusercontent.com/tute04/ALMA-MIA/main/WhatsApp%20Image%202026-01-29%20at%2000.18.25.jpeg" },
    { id: 1009, nombre: "Bolso Shopper Caramelo",   categoria: "Marroquinería", precio: "Consultar", descripcion: "Bolso shopper de cuero color caramelo, amplio y funcional, con doble asa.",                             imagen: "https://raw.githubusercontent.com/tute04/ALMA-MIA/main/WhatsApp%20Image%202026-01-29%20at%2000.18.49.jpeg" },
    { id: 1010, nombre: "Cartera Doble Cierre",     categoria: "Marroquinería", precio: "Consultar", descripcion: "Cartera de cuero con doble cierre y detalles en costura. Práctica y moderna.",                          imagen: "https://raw.githubusercontent.com/tute04/ALMA-MIA/main/WhatsApp%20Image%202026-01-29%20at%2000.19.25.jpeg" },

    // === AUTOR — NUEVOS 2026 ===
    { id: 1005, nombre: "Choker Boho Black",        categoria: "Autor", precio: "Consultar", descripcion: "Choker de gamuza negra con dije metálico central. Inspiración bohemia y moderna.",          imagen: "https://raw.githubusercontent.com/tute04/ALMA-MIA/main/WhatsApp%20Image%202026-01-29%20at%2000.16.58.jpeg" },
    { id: 1006, nombre: "Gargantilla Cristal Azul", categoria: "Autor", precio: "Consultar", descripcion: "Gargantilla con cuentas de cristal azul y detalles en plata. Toque delicado y elegante.",   imagen: "https://raw.githubusercontent.com/tute04/ALMA-MIA/main/WhatsApp%20Image%202026-01-29%20at%2000.17.37.jpeg" },
    { id: 1007, nombre: "Collar Dije Solitario",    categoria: "Autor", precio: "Consultar", descripcion: "Collar con dije único en forma de gota, montado en cordón de cuero natural.",               imagen: "https://raw.githubusercontent.com/tute04/ALMA-MIA/main/WhatsApp%20Image%202026-01-29%20at%2000.17.51.jpeg" },
    { id: 1011, nombre: "Choker Cuero Doble Vuelta",categoria: "Autor", precio: "Consultar", descripcion: "Choker de cuero marrón, doble vuelta, con dije central y terminaciones metálicas.",         imagen: "https://raw.githubusercontent.com/tute04/ALMA-MIA/main/WhatsApp%20Image%202026-01-29%20at%2000.21.00.jpeg" },
    { id: 1012, nombre: "Gargantilla Cuero Natural",categoria: "Autor", precio: "Consultar", descripcion: "Gargantilla de cuero natural con detalles en metal y cuentas. Estilo rústico.",              imagen: "https://raw.githubusercontent.com/tute04/ALMA-MIA/main/WhatsApp%20Image%202026-01-29%20at%2000.21.35.jpeg" },
    { id: 1013, nombre: "Collar Cuero & Metal",     categoria: "Autor", precio: "Consultar", descripcion: "Collar de cuero marrón con piezas metálicas y diseño geométrico. Único y artesanal.",       imagen: "https://raw.githubusercontent.com/tute04/ALMA-MIA/main/WhatsApp%20Image%202026-01-29%20at%2000.22.06.jpeg" },
    { id: 1015, nombre: "Collar Dije Circular",     categoria: "Autor", precio: "Consultar", descripcion: "Collar con dije circular de resina y cordón de cuero. Toque moderno y colorido.",            imagen: "https://raw.githubusercontent.com/tute04/ALMA-MIA/main/WhatsApp%20Image%202026-01-29%20at%2000.23.00.jpeg" },

    // === ACERO — NUEVOS 2026 ===
    { id: 1014, nombre: "Pulsera Acero Minimal",    categoria: "Acero", precio: "Consultar", descripcion: "Pulsera de acero quirúrgico, diseño minimalista y elegante. Ideal para uso diario.",         imagen: "https://raw.githubusercontent.com/tute04/ALMA-MIA/main/WhatsApp%20Image%202026-01-29%20at%2000.22.33.jpeg" },

    // === MARROQUINERÍA — CINTRONES ===
    { id: 308, nombre: "Cinturo­nes Rock Black",    categoria: "Marroquinería", precio: "Consultar", descripcion: "Colección tachas plateadas fondo negro.",                   imagen: "https://raw.githubusercontent.com/tute04/ALMA-MIA/main/WhatsApp%20Image%202025-12-23%20at%2021.44.57%20(4).jpeg" },
    { id: 309, nombre: "Cinturones Rock Suela",     categoria: "Marroquinería", precio: "Consultar", descripcion: "Cuero ecológico tono suela y dulce de leche.",               imagen: "https://raw.githubusercontent.com/tute04/ALMA-MIA/main/WhatsApp%20Image%202025-12-23%20at%2021.44.56%20(2).jpeg" },

    // === AUTOR — LOTE MADERA ===
    { id: 401, nombre: "Collares Tubos & Cordón",   categoria: "Autor", precio: "Consultar", descripcion: "Diseño artesanal con tubos de resina.",                              imagen: "https://raw.githubusercontent.com/tute04/ALMA-MIA/main/WhatsApp%20Image%202025-12-28%20at%2018.44.57%20(1).jpeg" },
    { id: 402, nombre: "Choker Trenzado Black",     categoria: "Autor", precio: "Consultar", descripcion: "Gamuza negra trenzada con cadena plateada.",                         imagen: "https://raw.githubusercontent.com/tute04/ALMA-MIA/main/WhatsApp%20Image%202025-12-24%20at%2017.07.44.jpeg" },
    { id: 403, nombre: "Choker Trenzado Camel",     categoria: "Autor", precio: "Consultar", descripcion: "Gamuza suela trenzada con cadena gruesa.",                           imagen: "https://raw.githubusercontent.com/tute04/ALMA-MIA/main/WhatsApp%20Image%202025-12-24%20at%2017.07.43.jpeg" },
    { id: 404, nombre: "Choker Trenzado Choco",     categoria: "Autor", precio: "Consultar", descripcion: "Gamuza marrón oscuro trenzada con metal.",                           imagen: "https://raw.githubusercontent.com/tute04/ALMA-MIA/main/WhatsApp%20Image%202025-12-24%20at%2017.07.43%20(1).jpeg" },
    { id: 405, nombre: "Lariats Cristales",         categoria: "Autor", precio: "Consultar", descripcion: "Collares largos anudados con cristales.",                            imagen: "https://raw.githubusercontent.com/tute04/ALMA-MIA/main/WhatsApp%20Image%202025-12-28%20at%2018.45.18.jpeg" },
    { id: 406, nombre: "Gargantillas Multi-hilos",  categoria: "Autor", precio: "Consultar", descripcion: "Multiples hilos encerados con terminales.",                          imagen: "https://raw.githubusercontent.com/tute04/ALMA-MIA/main/WhatsApp%20Image%202025-12-28%20at%2018.44.35.jpeg" },
    { id: 407, nombre: "Colgantes Gota Resina",     categoria: "Autor", precio: "Consultar", descripcion: "Cordón con dije gota de resina grande.",                             imagen: "https://raw.githubusercontent.com/tute04/ALMA-MIA/main/WhatsApp%20Image%202025-12-28%20at%2018.43.54.jpeg" },
    { id: 408, nombre: "Colgantes Círculo Resina",  categoria: "Autor", precio: "Consultar", descripcion: "Cordón grueso con dije circular jaspeado.",                          imagen: "https://raw.githubusercontent.com/tute04/ALMA-MIA/main/WhatsApp%20Image%202025-12-28%20at%2018.44.08.jpeg" },
    { id: 409, nombre: "Collar Donut Brown",        categoria: "Autor", precio: "Consultar", descripcion: "Multi-hilos beige con dona de resina.",                              imagen: "https://raw.githubusercontent.com/tute04/ALMA-MIA/main/WhatsApp%20Image%202025-12-28%20at%2018.43.44.jpeg" },
    { id: 410, nombre: "Collar Flor Metal & Gamuza",categoria: "Autor", precio: "Consultar", descripcion: "Gamuza azul con flor metálica grande.",                             imagen: "https://raw.githubusercontent.com/tute04/ALMA-MIA/main/WhatsApp%20Image%202025-12-28%20at%2018.46.44.jpeg" },
    { id: 411, nombre: "Collares Plumas & Dijes",   categoria: "Autor", precio: "Consultar", descripcion: "Tiras largas con plumas y dijes hamsa.",                             imagen: "https://raw.githubusercontent.com/tute04/ALMA-MIA/main/WhatsApp%20Image%202025-12-28%20at%2018.46.59.jpeg" },
    { id: 413, nombre: "Collares Cuerno Boho",      categoria: "Autor", precio: "Consultar", descripcion: "Dije cuerno/colmillo con cadena y gamuza.",                          imagen: "https://raw.githubusercontent.com/tute04/ALMA-MIA/main/WhatsApp%20Image%202025-12-28%20at%2018.46.10.jpeg" },
    { id: 414, nombre: "Collares Rectángulo Resina",categoria: "Autor", precio: "Consultar", descripcion: "Dije geométrico resina efecto carey/agua.",                          imagen: "https://raw.githubusercontent.com/tute04/ALMA-MIA/main/WhatsApp%20Image%202025-12-28%20at%2018.48.41.jpeg" },
    { id: 415, nombre: "Collares Piedra Natural",   categoria: "Autor", precio: "Consultar", descripcion: "Piedras naturales engarzadas en gamuza.",                            imagen: "https://raw.githubusercontent.com/tute04/ALMA-MIA/main/WhatsApp%20Image%202025-12-28%20at%2018.46.25.jpeg" },

    // === ACERO — LOTE ===
    { id: 412, nombre: "Rosario Pluma",             categoria: "Acero", precio: "Consultar", descripcion: "Cadena de bolitas acero con pluma.",                                 imagen: "https://raw.githubusercontent.com/tute04/ALMA-MIA/main/WhatsApp%20Image%202025-12-28%20at%2018.48.15.jpeg" },
    { id: 416, nombre: "Corbatero Cristal",         categoria: "Acero", precio: "Consultar", descripcion: "Cadena veneciana con gota de cristal.",                              imagen: "https://raw.githubusercontent.com/tute04/ALMA-MIA/main/WhatsApp%20Image%202025-12-28%20at%2018.47.54.jpeg" },

    // === MARROQUINERÍA — ANTERIORES ===
    { id: 203, nombre: "Sobre Camel Chain",         categoria: "Marroquinería", precio: "Consultar", descripcion: "Cuero natural color suela con detalle de cadena.",            imagen: "https://raw.githubusercontent.com/tute04/ALMA-MIA/main/WhatsApp%20Image%202025-12-21%20at%2009.50.21%20(10).jpeg" },
    { id: 204, nombre: "Bandolera Vintage",         categoria: "Marroquinería", precio: "Consultar", descripcion: "Cuero genuino efecto gastado artesanal.",                     imagen: "https://raw.githubusercontent.com/tute04/ALMA-MIA/main/WhatsApp%20Image%202025-12-21%20at%2009.50.21%20(11).jpeg" },
    { id: 205, nombre: "Portacelular Leo",          categoria: "Marroquinería", precio: "Consultar", descripcion: "Combinado cuero y pelo natural estampado.",                   imagen: "https://raw.githubusercontent.com/tute04/ALMA-MIA/main/WhatsApp%20Image%202025-12-21%20at%2009.50.21%20(12).jpeg" },
    { id: 206, nombre: "Bandolera Cream Gold",      categoria: "Marroquinería", precio: "Consultar", descripcion: "Cuero genuino combinado con grabado dorado.",                  imagen: "https://raw.githubusercontent.com/tute04/ALMA-MIA/main/WhatsApp%20Image%202025-12-21%20at%2009.50.21%20(13).jpeg" },
    { id: 101, nombre: "Hobo Bag Croco Rosa",       categoria: "Marroquinería", precio: "Consultar", descripcion: "Cuero genuino textura croco. Color rosa pastel.",             imagen: "https://raw.githubusercontent.com/tute04/ALMA-MIA/main/WhatsApp%20Image%202025-12-21%20at%2009.50.20%20(1).jpeg" },
    { id: 102, nombre: "Bandolera Suede Nude",      categoria: "Marroquinería", precio: "Consultar", descripcion: "Gamuza legítima (Cuero) con herraje plateado.",               imagen: "https://raw.githubusercontent.com/tute04/ALMA-MIA/main/WhatsApp%20Image%202025-12-21%20at%2009.50.20.jpeg" },
    { id: 201, nombre: "Tote Bag Gamuza Chocolate", categoria: "Marroquinería", precio: "Consultar", descripcion: "100% Cuero gamuza genuino. Gran capacidad.",                  imagen: "https://raw.githubusercontent.com/tute04/ALMA-MIA/main/WhatsApp%20Image%202025-12-21%20at%2009.50.20%20(5).jpeg" },
    { id: 208, nombre: "Billetera Lima & Cardholder",categoria: "Marroquinería",precio: "Consultar", descripcion: "Diseño elegante con tarjetero extraíble.",                    imagen: "https://raw.githubusercontent.com/tute04/ALMA-MIA/main/WhatsApp%20Image%202025-12-21%20at%2009.48.29%20(3).jpeg" },
    { id: 202, nombre: "Billeteras Texturadas",     categoria: "Marroquinería", precio: "Consultar", descripcion: "Cuero genuino texturado en colores vibrantes.",               imagen: "https://raw.githubusercontent.com/tute04/ALMA-MIA/main/WhatsApp%20Image%202025-12-21%20at%2009.48.30%20(1).jpeg" },
    { id: 207, nombre: "Bolso Everlast Negro",      categoria: "Marroquinería", precio: "Consultar", descripcion: "Estilo urbano deportivo. Nylon reforzado.",                   imagen: "https://raw.githubusercontent.com/tute04/ALMA-MIA/main/WhatsApp%20Image%202025-12-21%20at%2009.48.29%20(2).jpeg" },
    { id: 1,   nombre: "Tote Bag Urbano",           categoria: "Marroquinería", precio: "Consultar", descripcion: "Cierre frontal y herraje circular. Nude.",                    imagen: "https://raw.githubusercontent.com/tute04/ALMA-MIA/main/WhatsApp%20Image%202025-12-19%20at%2008.58.15.jpeg" },
    { id: 2,   nombre: "Bandolera Flap",            categoria: "Marroquinería", precio: "Consultar", descripcion: "Textura rugosa, tapa elegante. Camel.",                       imagen: "https://raw.githubusercontent.com/tute04/ALMA-MIA/main/WhatsApp%20Image%202025-12-19%20at%2008.58.12.jpeg" },
    { id: 3,   nombre: "Morral Sport",              categoria: "Marroquinería", precio: "Consultar", descripcion: "Correa ancha con letras. Estilo urbano.",                     imagen: "https://raw.githubusercontent.com/tute04/ALMA-MIA/main/WhatsApp%20Image%202025-12-19%20at%2008.58.12%20(1).jpeg" },
    { id: 5,   nombre: "Bandolera Nude",            categoria: "Marroquinería", precio: "Consultar", descripcion: "Detalles texturados y cierre superior.",                      imagen: "https://raw.githubusercontent.com/tute04/ALMA-MIA/main/WhatsApp%20Image%202025-12-19%20at%2008.58.13%20(1).jpeg" },
    { id: 39,  nombre: "Hobo Bag Aquarella",        categoria: "Marroquinería", precio: "Consultar", descripcion: "Negro charol brillante. Estilo 90s.",                         imagen: "https://raw.githubusercontent.com/tute04/ALMA-MIA/main/WhatsApp%20Image%202025-12-20%20at%2020.14.23.jpeg" },
    { id: 40,  nombre: "Bandolera Amayra",          categoria: "Marroquinería", precio: "Consultar", descripcion: "Negra nylon mate. Correa ancha.",                             imagen: "https://raw.githubusercontent.com/tute04/ALMA-MIA/main/WhatsApp%20Image%202025-12-20%20at%2020.46.19.jpeg" },
    { id: 41,  nombre: "Morral Polo Club",          categoria: "Marroquinería", precio: "Consultar", descripcion: "Cuero PU negro vertical. Unisex.",                            imagen: "https://raw.githubusercontent.com/tute04/ALMA-MIA/main/WhatsApp%20Image%202025-12-20%20at%2020.14.59.jpeg" },
    { id: 42,  nombre: "Camera Bag Glossy",         categoria: "Marroquinería", precio: "Consultar", descripcion: "Charol negro con doble cierre.",                              imagen: "https://raw.githubusercontent.com/tute04/ALMA-MIA/main/WhatsApp%20Image%202025-12-20%20at%2020.13.34.jpeg" },
    { id: 43,  nombre: "Mochila Cherry",            categoria: "Marroquinería", precio: "Consultar", descripcion: "Rojo vibrante texturado. Cierres metal.",                     imagen: "https://raw.githubusercontent.com/tute04/ALMA-MIA/main/WhatsApp%20Image%202025-12-20%20at%2020.37.27.jpeg" },
    { id: 44,  nombre: "Bandolera Dálmata",         categoria: "Marroquinería", precio: "Consultar", descripcion: "Pelo natural diseño manchas.",                                imagen: "https://raw.githubusercontent.com/tute04/ALMA-MIA/main/WhatsApp%20Image%202025-12-20%20at%2020.37.27%20(1).jpeg" },
    { id: 45,  nombre: "Bandolera Dark Leo",        categoria: "Marroquinería", precio: "Consultar", descripcion: "Pelo natural leopardo oscuro.",                               imagen: "https://raw.githubusercontent.com/tute04/ALMA-MIA/main/WhatsApp%20Image%202025-12-20%20at%2020.37.27%20(2).jpeg" },
    { id: 46,  nombre: "Tote Bag Glam",             categoria: "Marroquinería", precio: "Consultar", descripcion: "Cuero dorado y leopardo.",                                    imagen: "https://raw.githubusercontent.com/tute04/ALMA-MIA/main/WhatsApp%20Image%202025-12-20%20at%2020.37.30%20(1).jpeg" },
    { id: 47,  nombre: "Tote Reptil Camel",         categoria: "Marroquinería", precio: "Consultar", descripcion: "Cuero calado textura reptil.",                               imagen: "https://raw.githubusercontent.com/tute04/ALMA-MIA/main/WhatsApp%20Image%202025-12-20%20at%2020.37.30%20(2).jpeg" },
    { id: 48,  nombre: "Bandolera Snake",           categoria: "Marroquinería", precio: "Consultar", descripcion: "Negro metalizado textura reptil.",                            imagen: "https://raw.githubusercontent.com/tute04/ALMA-MIA/main/WhatsApp%20Image%202025-12-20%20at%2020.37.30%20(3).jpeg" },
    { id: 50,  nombre: "Bandolera Green",           categoria: "Marroquinería", precio: "Consultar", descripcion: "Combinada verde y reptil.",                                   imagen: "https://raw.githubusercontent.com/tute04/ALMA-MIA/main/WhatsApp%20Image%202025-12-20%20at%2020.37.30.jpeg" },

    // === AUTOR — ANTERIORES ===
    { id: 65,  nombre: "Luna Calada",               categoria: "Autor", precio: "Consultar", descripcion: "Dije luna creciente encaje.",                                         imagen: "https://raw.githubusercontent.com/tute04/ALMA-MIA/main/WhatsApp%20Image%202025-12-20%20at%2021.02.09%20(2).jpeg" },
    { id: 20,  nombre: "Collares Ágata",            categoria: "Autor", precio: "Consultar", descripcion: "Verde profundo y negro.",                                             imagen: "https://raw.githubusercontent.com/tute04/ALMA-MIA/main/WhatsApp%20Image%202025-12-19%20at%2009.07.10.jpeg" },
    { id: 53,  nombre: "Collares Piedra & Metal",   categoria: "Autor", precio: "Consultar", descripcion: "Cadenas largas y metal texturado.",                                   imagen: "https://raw.githubusercontent.com/tute04/ALMA-MIA/main/WhatsApp%20Image%202025-12-20%20at%2021.02.11%20(2).jpeg" },
    { id: 52,  nombre: "Collar Lapis Lazuli",       categoria: "Autor", precio: "Consultar", descripcion: "Piedra natural azul, dije candado.",                                  imagen: "https://raw.githubusercontent.com/tute04/ALMA-MIA/main/WhatsApp%20Image%202025-12-20%20at%2021.02.12%20(2).jpeg" },
    { id: 22,  nombre: "Óvalos Piedra",             categoria: "Autor", precio: "Consultar", descripcion: "Colgantes piedra pulida.",                                            imagen: "https://raw.githubusercontent.com/tute04/ALMA-MIA/main/WhatsApp%20Image%202025-12-19%20at%2008.58.20.jpeg" },
    { id: 62,  nombre: "Colgantes Vidrio",          categoria: "Autor", precio: "Consultar", descripcion: "Vidrio fusión, piezas únicas.",                                       imagen: "https://raw.githubusercontent.com/tute04/ALMA-MIA/main/WhatsApp%20Image%202025-12-20%20at%2021.02.10%20(2).jpeg" },
    { id: 66,  nombre: "Collar Ojo de Tigre",       categoria: "Autor", precio: "Consultar", descripcion: "Piedras naturales marrones.",                                         imagen: "https://raw.githubusercontent.com/tute04/ALMA-MIA/main/WhatsApp%20Image%202025-12-20%20at%2021.02.09.jpeg" },
    { id: 17,  nombre: "Luna Invertida",            categoria: "Autor", precio: "Consultar", descripcion: "Metal fundido y cuero.",                                              imagen: "https://raw.githubusercontent.com/tute04/ALMA-MIA/main/WhatsApp%20Image%202025-12-19%20at%2008.58.18.jpeg" },
    { id: 18,  nombre: "Esfera Jaula",              categoria: "Autor", precio: "Consultar", descripcion: "Dije geométrico con esfera interna.",                                 imagen: "https://raw.githubusercontent.com/tute04/ALMA-MIA/main/WhatsApp%20Image%202025-12-19%20at%2008.58.19.jpeg" },
    { id: 19,  nombre: "Rodajas Ágata",             categoria: "Autor", precio: "Consultar", descripcion: "Piedras naturales corte transversal.",                                imagen: "https://raw.githubusercontent.com/tute04/ALMA-MIA/main/WhatsApp%20Image%202025-12-19%20at%2008.58.20%20(1).jpeg" },
    { id: 21,  nombre: "Piedras Rústicas",          categoria: "Autor", precio: "Consultar", descripcion: "Cuarzo rosa y amatista en bruto.",                                    imagen: "https://raw.githubusercontent.com/tute04/ALMA-MIA/main/WhatsApp%20Image%202025-12-19%20at%2008.58.21%20(2).jpeg" },
    { id: 23,  nombre: "Cruces Piedra",             categoria: "Autor", precio: "Consultar", descripcion: "Cruz de piedra azul/negra.",                                          imagen: "https://raw.githubusercontent.com/tute04/ALMA-MIA/main/WhatsApp%20Image%202025-12-19%20at%2008.58.21%20(1).jpeg" },
    { id: 24,  nombre: "Cuerno Turquesa",           categoria: "Autor", precio: "Consultar", descripcion: "Estilo boho con cuentas madera.",                                     imagen: "https://raw.githubusercontent.com/tute04/ALMA-MIA/main/WhatsApp%20Image%202025-12-19%20at%2009.07.07%20(2).jpeg" },
    { id: 25,  nombre: "Cuerno Silver",             categoria: "Autor", precio: "Consultar", descripcion: "Amuleto plateado cuentas blancas.",                                   imagen: "https://raw.githubusercontent.com/tute04/ALMA-MIA/main/WhatsApp%20Image%202025-12-19%20at%2009.07.07%20(1).jpeg" },
    { id: 26,  nombre: "Flecos Jean",               categoria: "Autor", precio: "Consultar", descripcion: "Reciclaje textil denim.",                                             imagen: "https://raw.githubusercontent.com/tute04/ALMA-MIA/main/WhatsApp%20Image%202025-12-19%20at%2009.07.09%20(1).jpeg" },
    { id: 27,  nombre: "Flecos Gamuza",             categoria: "Autor", precio: "Consultar", descripcion: "Azul marino profundo.",                                               imagen: "https://raw.githubusercontent.com/tute04/ALMA-MIA/main/WhatsApp%20Image%202025-12-19%20at%2008.58.20%20(2).jpeg" },
    { id: 28,  nombre: "Dije Cuadrado",             categoria: "Autor", precio: "Consultar", descripcion: "Geometría con fleco denim.",                                          imagen: "https://raw.githubusercontent.com/tute04/ALMA-MIA/main/WhatsApp%20Image%202025-12-19%20at%2009.07.09.jpeg" },
    { id: 29,  nombre: "Aro Maxi Jean",             categoria: "Autor", precio: "Consultar", descripcion: "Círculo grande con tiras mixtas.",                                    imagen: "https://raw.githubusercontent.com/tute04/ALMA-MIA/main/WhatsApp%20Image%202025-12-19%20at%2009.07.09%20(2).jpeg" },
    { id: 30,  nombre: "Set Pulseras Jean",         categoria: "Autor", precio: "Consultar", descripcion: "Rígidas forradas en jean.",                                           imagen: "https://raw.githubusercontent.com/tute04/ALMA-MIA/main/WhatsApp%20Image%202025-12-19%20at%2009.07.08.jpeg" },
    { id: 49,  nombre: "Brazaletes Denim",          categoria: "Autor", precio: "Consultar", descripcion: "Puños bordados a mano.",                                              imagen: "https://raw.githubusercontent.com/tute04/ALMA-MIA/main/WhatsApp%20Image%202025-12-20%20at%2020.37.30%20(4).jpeg" },
    { id: 51,  nombre: "Pulseras Roll-on",          categoria: "Autor", precio: "Consultar", descripcion: "Set mostacillas crochet.",                                            imagen: "https://raw.githubusercontent.com/tute04/ALMA-MIA/main/WhatsApp%20Image%202025-12-20%20at%2021.02.13.jpeg" },
    { id: 54,  nombre: "Collar Tejido Nacar",       categoria: "Autor", precio: "Consultar", descripcion: "Tejido para atar con bolitas de nácar.",                              imagen: "https://raw.githubusercontent.com/tute04/ALMA-MIA/main/WhatsApp%20Image%202025-12-20%20at%2021.02.12%20(1).jpeg" },
    { id: 55,  nombre: "Collar Tejido Cristales",   categoria: "Autor", precio: "Consultar", descripcion: "Gargantilla delicada cristales salpicados.",                          imagen: "https://raw.githubusercontent.com/tute04/ALMA-MIA/main/WhatsApp%20Image%202025-12-20%20at%2021.02.11%20(1).jpeg" },
    { id: 56,  nombre: "Collar Gota Negra",         categoria: "Autor", precio: "Consultar", descripcion: "Ágata negra lágrima.",                                               imagen: "https://raw.githubusercontent.com/tute04/ALMA-MIA/main/WhatsApp%20Image%202025-12-20%20at%2021.02.12.jpeg" },
    { id: 57,  nombre: "Gargantilla Tejida Cristales",categoria:"Autor", precio: "Consultar", descripcion: "Hilo invisible con cristales.",                                      imagen: "https://raw.githubusercontent.com/tute04/ALMA-MIA/main/WhatsApp%20Image%202025-12-20%20at%2021.02.12%20(3).jpeg" },
    { id: 59,  nombre: "Collares Corbateros",       categoria: "Autor", precio: "Consultar", descripcion: "Estilo Y con borlas de gamuza.",                                      imagen: "https://raw.githubusercontent.com/tute04/ALMA-MIA/main/WhatsApp%20Image%202025-12-20%20at%2021.02.13%20(1).jpeg" },
    { id: 60,  nombre: "Collar Rojo Tassel",        categoria: "Autor", precio: "Consultar", descripcion: "Gamuza roja con borla larga.",                                        imagen: "https://raw.githubusercontent.com/tute04/ALMA-MIA/main/WhatsApp%20Image%202025-12-20%20at%2021.03.02.jpeg" },
    { id: 64,  nombre: "Collar Verde Etnico",       categoria: "Autor", precio: "Consultar", descripcion: "Cuentas facetadas verdes.",                                           imagen: "https://raw.githubusercontent.com/tute04/ALMA-MIA/main/WhatsApp%20Image%202025-12-20%20at%2021.02.09%20(1).jpeg" },
    { id: 38,  nombre: "Sombreros Pilusoy",         categoria: "Autor", precio: "Consultar", descripcion: "Tejidos artesanales.",                                                imagen: "https://raw.githubusercontent.com/tute04/ALMA-MIA/main/WhatsApp%20Image%202025-12-19%20at%2009.07.07.jpeg" },
    { id: 31,  nombre: "Trenzado Rojo",             categoria: "Autor", precio: "Consultar", descripcion: "Cadena gruesa y gamuza.",                                             imagen: "https://raw.githubusercontent.com/tute04/ALMA-MIA/main/WhatsApp%20Image%202025-12-19%20at%2008.58.21%20(4).jpeg" },
    { id: 35,  nombre: "Trenzado Cintas",           categoria: "Autor", precio: "Consultar", descripcion: "Mix de cintas azul y marrón.",                                        imagen: "https://raw.githubusercontent.com/tute04/ALMA-MIA/main/WhatsApp%20Image%202025-12-19%20at%2008.58.21%20(3).jpeg" },
    { id: 36,  nombre: "Chokers Cuentas",           categoria: "Autor", precio: "Consultar", descripcion: "Mix de mostacillas facetadas.",                                       imagen: "https://raw.githubusercontent.com/tute04/ALMA-MIA/main/WhatsApp%20Image%202025-12-19%20at%2008.58.15%20(2).jpeg" },
    { id: 37,  nombre: "Dijes Abstractos",          categoria: "Autor", precio: "Consultar", descripcion: "Colgantes irregulares plateados.",                                    imagen: "https://raw.githubusercontent.com/tute04/ALMA-MIA/main/WhatsApp%20Image%202025-12-19%20at%2009.07.06.jpeg" },

    // === ACERO — ANTERIORES ===
    { id: 302, nombre: "Aros Argolla Texturada",    categoria: "Acero", precio: "Consultar", descripcion: "Acero quirúrgico. Acabado trabajado brillante.",                      imagen: "https://raw.githubusercontent.com/tute04/ALMA-MIA/main/WhatsApp%20Image%202025-12-23%20at%2021.44.55%20(1).jpeg" },
    { id: 63,  nombre: "Pulseras Strass Red",       categoria: "Acero", precio: "Consultar", descripcion: "Estilo tennis, cristales rojos.",                                     imagen: "https://raw.githubusercontent.com/tute04/ALMA-MIA/main/WhatsApp%20Image%202025-12-20%20at%2021.02.10%20(1).jpeg" },
    { id: 6,   nombre: "Libélula Acero",            categoria: "Acero", precio: "Consultar", descripcion: "Dije libélula detalles dorados.",                                     imagen: "https://raw.githubusercontent.com/tute04/ALMA-MIA/main/WhatsApp%20Image%202025-12-19%20at%2008.58.15%20(3).jpeg" },
    { id: 7,   nombre: "Corazón Simple",            categoria: "Acero", precio: "Consultar", descripcion: "Silueta corazón minimalista.",                                        imagen: "https://raw.githubusercontent.com/tute04/ALMA-MIA/main/WhatsApp%20Image%202025-12-19%20at%2008.58.16%20(1).jpeg" },
    { id: 8,   nombre: "Corazón Puff",              categoria: "Acero", precio: "Consultar", descripcion: "Dije corazón con volumen.",                                           imagen: "https://raw.githubusercontent.com/tute04/ALMA-MIA/main/WhatsApp%20Image%202025-12-19%20at%2008.58.16%20(2).jpeg" },
    { id: 9,   nombre: "Cruz Barroca",              categoria: "Acero", precio: "Consultar", descripcion: "Cruz detalles corazones.",                                            imagen: "https://raw.githubusercontent.com/tute04/ALMA-MIA/main/WhatsApp%20Image%202025-12-19%20at%2008.58.16.jpeg" },
    { id: 10,  nombre: "Dije Circular",             categoria: "Acero", precio: "Consultar", descripcion: "Círculo textura corazones.",                                          imagen: "https://raw.githubusercontent.com/tute04/ALMA-MIA/main/WhatsApp%20Image%202025-12-19%20at%2008.58.17.jpeg" },
    { id: 11,  nombre: "San Benito",                categoria: "Acero", precio: "Consultar", descripcion: "Medalla protectora.",                                                 imagen: "https://raw.githubusercontent.com/tute04/ALMA-MIA/main/WhatsApp%20Image%202025-12-19%20at%2008.58.17%20(2).jpeg" },
    { id: 12,  nombre: "Árbol de la Vida",          categoria: "Acero", precio: "Consultar", descripcion: "Corte láser fondo negro.",                                            imagen: "https://raw.githubusercontent.com/tute04/ALMA-MIA/main/WhatsApp%20Image%202025-12-19%20at%2008.58.17%20(1).jpeg" },
    { id: 13,  nombre: "Dije Redondo",              categoria: "Acero", precio: "Consultar", descripcion: "Diseño trenzado circular.",                                           imagen: "https://raw.githubusercontent.com/tute04/ALMA-MIA/main/WhatsApp%20Image%202025-12-19%20at%2008.58.16%20(3).jpeg" },
    { id: 14,  nombre: "Cruz Cuadrada",             categoria: "Acero", precio: "Consultar", descripcion: "Textura geométrica red.",                                             imagen: "https://raw.githubusercontent.com/tute04/ALMA-MIA/main/WhatsApp%20Image%202025-12-19%20at%2008.58.16%20(4).jpeg" },
    { id: 15,  nombre: "Cadena Snake",              categoria: "Acero", precio: "Consultar", descripcion: "Tejido plano fluido.",                                                imagen: "https://raw.githubusercontent.com/tute04/ALMA-MIA/main/WhatsApp%20Image%202025-12-19%20at%2008.58.19%20(1).jpeg" },
    { id: 58,  nombre: "Brazaletes Cuffs",          categoria: "Acero", precio: "Consultar", descripcion: "Esclavas anchas rígidas.",                                            imagen: "https://raw.githubusercontent.com/tute04/ALMA-MIA/main/WhatsApp%20Image%202025-12-20%20at%2021.02.34.jpeg" },
    { id: 61,  nombre: "Tobilleras Margaritas",     categoria: "Acero", precio: "Consultar", descripcion: "Delicadas con flores.",                                               imagen: "https://raw.githubusercontent.com/tute04/ALMA-MIA/main/WhatsApp%20Image%202025-12-20%20at%2021.02.10.jpeg" },
];
